version: "2"

linters:
  default: all

  disable:
    - err113
    - gomodguard
    - ireturn
    - noinlineerr
    - revive
    - wsl
  
  exclusions:
    paths:
      - ".+_test.go"

  settings:
    cyclop:
      max-complexity: 15
    funlen:
      lines: 100
    tagliatelle:
      case:
        ignored-fields:
          - Data
    wrapcheck:
      extra-ignore-sigs:
        - .WriteValue

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
