name: Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checks:
    name: Run checks
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['1.18', '1.22', '1.23', '1.24']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      run: go test -v ./...

    - name: Run linters
      uses: golangci/golangci-lint-action@v8
      with:
        version: v2.2.2
